name: release wheel

defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  release-wheel:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_finch_mlir
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: nullplay/Finch-mlir
          run-id: 11392793236

      - name: Release current commit
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*.whl'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: latest
          body: Latest release
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          artifactErrorsFailBuild: true
